version: "3.9"

services:
  go-rest-clean-boilerplate:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
  mongodb:
      image: mongo:3.6
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=mydb
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      ports:
        - 27017:27017
